### PR TITLE
Question about tuples with trailing commas

### PR DESCRIPTION
**Pull request by peterjoel**

### CODE REVIEW

**Review by dtolnay — COMMENTED** [review]
Thanks! I've been wanting to add a question about `(T)` vs `(T,)` -- #3. I like your juxtaposition of `(u32)` and `(i32,)` vs `(u32, u32)` and `(i32, i32,)`.

Would it be possible to come up with a similarly concise question without macro_rules? Macros are a complicated topic and I think it distracts from the point of the question. Someone shouldn't have to understand macros to answer this.

**Comment by peterjoel** [comment]
Sure. Expanding the macros results in 34 lines of code, which is one line shorter than [the longest existing example](https://github.com/dtolnay/rust-quiz/blob/master/questions/021-closure-or-logical-or.rs).

**Review by dtolnay — APPROVED** [review]
Thanks!

**Comment by dtolnay** [comment]
Published in https://dtolnay.github.io/rust-quiz/29.

**Pull request merged**
