### PR TITLE
A first stab at explaining late-bound lifetimes

### PR DESCRIPTION
**Pull request by peterjoel**
I'm fairly sure that the main idea of this edit is correct. There could be some inaccurate details or areas that could be explained better.

### CODE REVIEW

**Comment by peterjoel** [comment]
This might be relevant, and perhaps indicates that HRTB are not the whole story: https://github.com/rust-lang/rust/blob/8301de16dafc81a3b5d94aa0707ad83bdb56a599/src/librustc/infer/mod.rs#L352-L363

**Comment by peterjoel** [comment]
Also this: https://internals.rust-lang.org/t/late-bound-lifetimes-hrtb-related/8376, which links to these very old posts:

* http://smallcultfollowing.com/babysteps/blog/2013/10/29/intermingled-parameter-lists/
* http://smallcultfollowing.com/babysteps/blog/2013/11/04/intermingled-parameter-lists/

**Review by dtolnay — APPROVED** [review]
Wow, the behavior makes some sense now! Thanks for providing this explanation.

**Comment by peterjoel** [comment]
I didn't expect you to merge it straight away! Like I said, I'm not _100%_ certain about what I wrote there.

**Comment by dtolnay** [comment]
That's fine, we can iterate on it as needed.

I made a couple fixes in https://github.com/dtolnay/rust-quiz/compare/6350e076fba5baaa3d3f7f3650b8cd71966c2685...242cbb60d2fa14cb03f6401b877937336971429a. Most importantly, I believe you were on the right track but got the conclusion backward at the end. You had written:

> The signature `fn f<'a>()` has an early bound lifetime parameter because the lifetime `'a` is not used and therefore it doesn't matter what it is. The signature `fn g<'a: 'a>()` has a late bound lifetime parameter because it is constrained

In actuality, `f` is the late bound one and `g` is the early bound one as we can tell from the error message.

```console
error: cannot specify lifetime arguments explicitly if late bound lifetime parameters are present
 --> questions/011.rs:5:18
  |
5 |     let pf = f::<'static> as fn();
  |                  ^^^^^^^
```

**Comment by peterjoel** [comment]
Aha, yes. Looks like mixed myself up over a double negation.

**Pull request merged**
